service: cron-jobs

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: 
        - Fn::ImportValue: process-challenges-queueArn

params:
  default:
    node_env: development
  prod:
    node_env: production
  dev:
    node_env: development
  local:
    node_env: local

functions:
  domain5:
    runtime: nodejs20.x
    timeout: 29
    handler: ./src/domains/domain5/index.handler
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: false
    environment:
      NODE_ENV: ${param:node_env}
      QUEUE_URL:
        Fn::ImportValue: process-challenges-queueUrl
      MONGO_URI: ${env:MONGO_URI}
      RIOT_API_URL: ${env:RIOT_API_URL}
      RIOT_API_KEY: ${env:RIOT_API_KEY}

plugins:
  - serverless-offline
