service: cron-jobs

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: 
        - Fn::ImportValue: domain1-queueArn

functions:
  domain5:
    runtime: nodejs20.x
    handler: ./src/domains/domain5/index.handler
    events:
      - schedule: rate(3 minutes)
    environment:
      QUEUE_URL:
        Fn::ImportValue: domain1-queueUrl

plugins:
  - serverless-offline
